version: '3'

services:
  gzserver:
    image: ghcr.io/tiiuae/tii-gzserver:2.0.0
    command: empty.world
    environment:
      - PX4_SIM_USE_TCP_SERVER=1
    volumes:
      - ./gz-models:/gz-models
      - ./gz-plugins:/gz-plugins
      - ./gz-world:/gz-world
  px401:
    image: ghcr.io/tiiuae/tii-px4-sitl:sha-7e86f65
    environment:
      - DRONE_DEVICE_ID=drone01
      - SIMULATION=1
      - PX4_SIM_USE_TCP_SERVER=1 
  micrortps01:
    image: ghcr.io/tiiuae/tii-micrortps-agent:sha-cccdcbc-1
    network_mode: service:px401
    environment:
      - DRONE_DEVICE_ID=drone01
      - SIMULATION=1
      - PX4_SIM_USE_TCP_SERVER=1
  octomap:
    image: ghcr.io/tiiuae/tii-octomap-server2:sha-ed55cc2-1
    environment:
      - DRONE_DEVICE_ID=drone01
      - SIMULATION=1
      - PX4_SIM_USE_TCP_SERVER=1 
  rplidar:
    image: ghcr.io/tiiuae/tii-rplidar:sha-3c21ad7
    environment:
      - DRONE_DEVICE_ID=drone01
      - SIMULATION=1
      - PX4_SIM_USE_TCP_SERVER=1 
  fognav:
    image: ghcr.io/tiiuae/tii-fog-navigation:sha-0967171
    network_mode: service:px401
    environment:
      - DRONE_DEVICE_ID=drone01
      - SIMULATION=1
      - PX4_SIM_USE_TCP_SERVER=1 
